alias gf='git fetch --all --prune'
alias gl='git log --oneline'
alias gb='git branch -v'
alias gbd='git branch -D'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gpullo='git pull origin'
alias gpusho='git push origin'
alias ptest='pytest -s --disable-warnings --tb=short -m'
